### ISSUE TITLE
python gui.py

### ISSUE THREAD

**Issue by xiaoyang666** [liuyf5231/opendriveparser#1]
I have a problem when i use python gui.py

Traceback (most recent call last):
  File "opendrive2lanelet/io/gui.py", line 15, in <module>
    from opendrive2lanelet.opendriveparser.parser import parse_opendrive
  File "/home/yang/opendriveparser/opendrive2lanelet/opendriveparser/parser.py", line 6, in <module>
    from opendrive2lanelet.opendriveparser.elements.road import Road
  File "/home/yang/opendriveparser/opendrive2lanelet/opendriveparser/elements/road.py", line 3, in <module>
    from opendrive2lanelet.opendriveparser.elements.roadPlanView import PlanView
  File "/home/yang/opendriveparser/opendrive2lanelet/opendriveparser/elements/roadPlanView.py", line 251
    f"Tried to calculate a position outside of the borders of the reference path at s={s_pos}"
                                                                                             ^
SyntaxError: invalid syntax

**Comment by vtalpaert** [comment]
Hello @xiaoyang666, are you using python3.6 or higher ?

**Comment by yuewenqi** [comment]
hi，i have a problem when i use python gui.py it always flash back when i click the ‘expor..’ or 'view' button. i also can not find 'OSMConverter'in convert.py,i need your help,please 
This will help me a lot,thanks.
