### ISSUE TITLE
No module named 'commonroad'

### ISSUE THREAD

**Issue by YYangjlu** [liuyf5231/opendriveparser#2]
Traceback (most recent call last):
  File "C:/Users/dell/Desktop/opendriveparser-master/opendrive2lanelet/io/gui.py", line 16, in <module>
    from opendrive2lanelet.network import Network
  File "C:\Users\dell\Desktop\opendriveparser-master\opendrive2lanelet\network.py", line 7, in <module>
    from commonroad.scenario.scenario import Scenario
ModuleNotFoundError: No module named 'commonroad'

**Comment by liuyf5231** [comment]
you need to install commonroad module first.

`pip3 install -i https://pypi.douban.com/simple/ -r requirements.txt`
